/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package sk.stu.fiit;

import javax.swing.JOptionPane;

public class CheckerView extends javax.swing.JFrame {
    
    /** Creates new form Find */
    public CheckerView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regexTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        stringTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        caseCB = new javax.swing.JCheckBox();
        checkBtn = new javax.swing.JButton();
        cleanBtn = new javax.swing.JButton();
        trimBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("RegEx:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(regexTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 221, -1));

        stringTA.setColumns(20);
        stringTA.setRows(5);
        jScrollPane1.setViewportView(stringTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel2.setText("String:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 20));

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        caseCB.setText("Case sensitive");
        caseCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        caseCB.setPreferredSize(new java.awt.Dimension(100, 30));
        jToolBar1.add(caseCB);

        checkBtn.setText("Check");
        checkBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        checkBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkBtnMouseReleased(evt);
            }
        });
        jToolBar1.add(checkBtn);

        cleanBtn.setText("Clean");
        cleanBtn.setFocusable(false);
        cleanBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cleanBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        cleanBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cleanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cleanBtnMouseReleased(evt);
            }
        });
        jToolBar1.add(cleanBtn);

        trimBtn.setText("Trim");
        trimBtn.setFocusable(false);
        trimBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        trimBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        trimBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        trimBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                trimBtnMouseReleased(evt);
            }
        });
        jToolBar1.add(trimBtn);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBtnMouseReleased
        // TODO add your handling code here:
        String regex = regexTF.getText();
        String givenString = stringTA.getText();
        boolean caseSens = caseCB.isSelected();
        if(Checker.check(regex, givenString, caseSens)){
            JOptionPane.showMessageDialog(rootPane, "OK");
        } else{
            JOptionPane.showMessageDialog(rootPane, "NG");
        }
        
    }//GEN-LAST:event_checkBtnMouseReleased

    private void cleanBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanBtnMouseReleased
        // TODO add your handling code here:
        String givenString = stringTA.getText();
        givenString = givenString.replaceAll("[^\\n\\r\\t\\p{Print}]", "");
        stringTA.setText(givenString);
    }//GEN-LAST:event_cleanBtnMouseReleased

    private void trimBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trimBtnMouseReleased
        // TODO add your handling code here:
        String givenString = stringTA.getText();
        givenString = givenString.trim();
        stringTA.setText(givenString);
    }//GEN-LAST:event_trimBtnMouseReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckerView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox caseCB;
    private javax.swing.JButton checkBtn;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField regexTF;
    private javax.swing.JTextArea stringTA;
    private javax.swing.JButton trimBtn;
    // End of variables declaration//GEN-END:variables
    
}
